[app]
key = "this is your app key"
name = "cmdb"

[app.http]
host = "0.0.0.0"
port = "8050"

[app.grpc]
host = "0.0.0.0"
port = "18050"

[mysql]
database = "demo"
host = "127.0.0.1"
password = "123456"
port = "3306"
username = "demo"

[log]
format = "text"
level = "debug"
path = "logs"
to = "stdout"
